### ISSUE TITLE
Start a new match afterwards

### ISSUE THREAD

**Issue by chmiiller** [olrafa/nodal-point#1]
It would be nice to be able to immediately start a new match after the current one is over =)

Maybe after implementation of https://github.com/rafaelrolivares/tennis/blob/e6be1fe6829daf6818f014257af10fb100439752/venv/main.py#L101

**Comment by olrafa** [comment]
Will be implemented soon. We'll let the user select if they want a single match or a tournament, then if it's a tournament we'll have options for how many players (always a power of two).

I'm working on the tournament logic, but in the mean time I'll just add inquirer and let users choose between women's or men's tennis.

**Comment by olrafa** [comment]
Closed! Users can now select to play either a single match or a four-player tournament, which will play fully and then exit the process.

The plan is to get to up to 16 players, but let's see.
